// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjp5BSWjSQDbMF4gT8cn4EoL5zVMgM14',
    appId: '1:995840306273:web:22a8738763023c8d0e4e20',
    messagingSenderId: '995840306273',
    projectId: 'wonwoo-ac6a2',
    authDomain: 'wonwoo-ac6a2.firebaseapp.com',
    storageBucket: 'wonwoo-ac6a2.appspot.com',
    measurementId: 'G-3SR1RYNNGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2hGZIRjigZ48uyDTymMMW945LIx9E3d8',
    appId: '1:995840306273:android:fe54045f9e33045f0e4e20',
    messagingSenderId: '995840306273',
    projectId: 'wonwoo-ac6a2',
    storageBucket: 'wonwoo-ac6a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRc6uu9TPMkgnRdaAwdOyAduOasIBCh6Y',
    appId: '1:995840306273:ios:efbee044415ee8c90e4e20',
    messagingSenderId: '995840306273',
    projectId: 'wonwoo-ac6a2',
    storageBucket: 'wonwoo-ac6a2.appspot.com',
    iosClientId: '995840306273-2rscnqmdj3a9iqhbntheuso06tnkasnl.apps.googleusercontent.com',
    iosBundleId: 'com.wonwookorea.wonwoo',
  );
}
